<form method="post" action="<?php echo $this->url(array('action' => $this->action))?>">
  
  <input type="hidden" name="id" value="<?php echo $this->id ?>" />
  
  <dl>
    <dt><label for="title">Name</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'name')?>
      <input type="text" name="form[name]" id="name" value="<?php echo $this->escape($this->form['name'])?>" />
    </dd>
  </dl>
  
  <dl>
    <dd>
      <input type="submit" value="<?php echo $this->action?>" />
    </dd>
  </dl>
</form>